// Code generated by "stringer -type=TaskStatus"; DO NOT EDIT.

package configurablecommand

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pending-0]
	_ = x[Canceled-1]
	_ = x[Started-2]
	_ = x[Succeeded-3]
	_ = x[Failed-4]
}

const _TaskStatus_name = "PendingCanceledStartedSucceededFailed"

var _TaskStatus_index = [...]uint8{0, 7, 15, 22, 31, 37}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
