// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package bot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ListenTo-0]
	_ = x[ReplyTo-1]
	_ = x[DirectMessage-2]
}

const _MsgType_name = "ListenToReplyToDirectMessage"

var _MsgType_index = [...]uint8{0, 8, 15, 28}

func (i MsgType) String() string {
	if i < 0 || i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
